/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;
import calculadora.clsOperaciones;
import calculadora.clsArchivo;
import java.util.Date;

/**
 *
 * @author Renato
 */
public class CLDMform extends javax.swing.JFrame {
    clsOperaciones op = new clsOperaciones();
    clsArchivo arch = new clsArchivo();
    int opcion =0;
    /**
     * Creates new form CLDM
     */
    public CLDMform() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOperador = new javax.swing.JTextField();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btmas = new javax.swing.JButton();
        btmenos = new javax.swing.JButton();
        tbmulti = new javax.swing.JButton();
        btdivi = new javax.swing.JButton();
        tb0 = new javax.swing.JButton();
        btpunto = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA");
        setBackground(new java.awt.Color(0, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(500, 50));

        txtOperador.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtOperador.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOperadorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOperadorKeyTyped(evt);
            }
        });

        bt1.setBackground(new java.awt.Color(16, 57, 90));
        bt1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt1.setForeground(new java.awt.Color(90, 90, 90));
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        bt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bt1KeyPressed(evt);
            }
        });

        bt2.setBackground(new java.awt.Color(16, 57, 90));
        bt2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt2.setForeground(new java.awt.Color(90, 90, 90));
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setBackground(new java.awt.Color(16, 57, 90));
        bt3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt3.setForeground(new java.awt.Color(90, 90, 90));
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setBackground(new java.awt.Color(16, 57, 90));
        bt4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt4.setForeground(new java.awt.Color(90, 90, 90));
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setBackground(new java.awt.Color(16, 57, 90));
        bt5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt5.setForeground(new java.awt.Color(90, 90, 90));
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setBackground(new java.awt.Color(16, 57, 90));
        bt6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt6.setForeground(new java.awt.Color(90, 90, 90));
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt7.setBackground(new java.awt.Color(16, 57, 90));
        bt7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt7.setForeground(new java.awt.Color(90, 90, 90));
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt8.setBackground(new java.awt.Color(16, 57, 90));
        bt8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt8.setForeground(new java.awt.Color(90, 90, 90));
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt9.setBackground(new java.awt.Color(16, 57, 90));
        bt9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        bt9.setForeground(new java.awt.Color(90, 90, 90));
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        btmas.setBackground(new java.awt.Color(16, 57, 90));
        btmas.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btmas.setForeground(new java.awt.Color(90, 90, 90));
        btmas.setText("+");
        btmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmasActionPerformed(evt);
            }
        });

        btmenos.setBackground(new java.awt.Color(16, 57, 90));
        btmenos.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btmenos.setForeground(new java.awt.Color(90, 90, 90));
        btmenos.setText("-");
        btmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmenosActionPerformed(evt);
            }
        });

        tbmulti.setBackground(new java.awt.Color(16, 57, 90));
        tbmulti.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        tbmulti.setForeground(new java.awt.Color(90, 90, 90));
        tbmulti.setText("*");
        tbmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmultiActionPerformed(evt);
            }
        });

        btdivi.setBackground(new java.awt.Color(16, 57, 90));
        btdivi.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btdivi.setForeground(new java.awt.Color(90, 90, 90));
        btdivi.setText("/");
        btdivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdiviActionPerformed(evt);
            }
        });

        tb0.setBackground(new java.awt.Color(16, 57, 90));
        tb0.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        tb0.setForeground(new java.awt.Color(90, 90, 90));
        tb0.setText("0");
        tb0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb0ActionPerformed(evt);
            }
        });

        btpunto.setBackground(new java.awt.Color(16, 57, 90));
        btpunto.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btpunto.setForeground(new java.awt.Color(90, 90, 90));
        btpunto.setText(".");
        btpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpuntoActionPerformed(evt);
            }
        });

        btigual.setBackground(new java.awt.Color(16, 57, 90));
        btigual.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        btigual.setForeground(new java.awt.Color(90, 90, 90));
        btigual.setText("=");
        btigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigualActionPerformed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(0, 0, 0));
        lb1.setText("Respuesta");

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Opciones");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Historial");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Ayuda");

        jMenuItem3.setText("Manual de uso");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tb0)
                                            .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(btpunto)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btigual)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btmenos)
                                    .addComponent(btmas)
                                    .addComponent(tbmulti)
                                    .addComponent(btdivi)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40))
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmenos)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbmulti)
                    .addComponent(bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btdivi)
                    .addComponent(tb0)
                    .addComponent(btpunto)
                    .addComponent(btigual))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//evento para que solo reciba numeros y no letras
    
   
    
    private void txtOperadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperadorKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_txtOperadorKeyTyped

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        txtOperador.setText(txtOperador.getText()+"1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
         txtOperador.setText(txtOperador.getText()+"2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        txtOperador.setText(txtOperador.getText()+"3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
       txtOperador.setText(txtOperador.getText()+"4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
      txtOperador.setText(txtOperador.getText()+"5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
    txtOperador.setText(txtOperador.getText()+"6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
     txtOperador.setText(txtOperador.getText()+"7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
       txtOperador.setText(txtOperador.getText()+"8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
     txtOperador.setText(txtOperador.getText()+"9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void tb0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb0ActionPerformed
       txtOperador.setText(txtOperador.getText()+"0");
    }//GEN-LAST:event_tb0ActionPerformed

    private void btpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpuntoActionPerformed
        txtOperador.setText(txtOperador.getText()+".");
    }//GEN-LAST:event_btpuntoActionPerformed

    private void bt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bt1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt1KeyPressed
// suma
    private void btmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmasActionPerformed
        op.setN1(Double.parseDouble(this.txtOperador.getText()));
        opcion =1;
       txtOperador.setText(" ");
    }//GEN-LAST:event_btmasActionPerformed
//resta
    private void btmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmenosActionPerformed
         op.setN1(Double.parseDouble(this.txtOperador.getText()));
        opcion =2;
        txtOperador.setText(" ");
    }//GEN-LAST:event_btmenosActionPerformed
//multiplicacion
    private void tbmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmultiActionPerformed
        op.setN1(Double.parseDouble(this.txtOperador.getText()));
        opcion =3;
        txtOperador.setText(" ");
    }//GEN-LAST:event_tbmultiActionPerformed
//divicion
    private void btdiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdiviActionPerformed
        op.setN1(Double.parseDouble(this.txtOperador.getText()));
        opcion =4;
        txtOperador.setText(" ");
    }//GEN-LAST:event_btdiviActionPerformed

    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
    
       
        
       switch(opcion){
            case 1:
                 op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.adicion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" + "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 2:
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.sustraccion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" - "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 3:
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.multiplicacion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" * "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 4: 
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.divicion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" / "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
        }
    }//GEN-LAST:event_btigualActionPerformed

    private void txtOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperadorKeyPressed
       if(evt.VK_PLUS == evt.getKeyCode()){
            op.setN1(Double.parseDouble(this.txtOperador.getText()));
            opcion =1;
            
            txtOperador.setText(" ");
       }else if(evt.VK_MINUS == evt.getKeyCode()){
            op.setN1(Double.parseDouble(this.txtOperador.getText()));
            opcion =2;
            
            txtOperador.setText(" ");
       } 
       else if(evt.VK_MULTIPLY == evt.getKeyCode()){
            op.setN1(Double.parseDouble(this.txtOperador.getText()));
            opcion =3;
            
            txtOperador.setText(" ");
       }  else if(evt.VK_DIVIDE == evt.getKeyCode()){
            op.setN1(Double.parseDouble(this.txtOperador.getText()));
            opcion =3;
            
            txtOperador.setText(" ");
       } 
       else if(evt.VK_ENTER == evt.getKeyCode()){
               
        
       switch(opcion){
            case 1:
                 op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.adicion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" + "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 2:
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.sustraccion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" - "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 3:
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.multiplicacion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" * "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
            case 4: 
                op.setN2(Double.parseDouble(this.txtOperador.getText()));
                 op.divicion();
                 this.lb1.setText(op.getResult()+"");
                 arch.escribir("Historial_calculadora.text",""+op.getN1()+" / "+op.getN2()+" = "+op.getResult());
                 txtOperador.setText(" ");
                break;
        }
       }   
    }//GEN-LAST:event_txtOperadorKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        
        arch.abrirarchivo("Historial_calculadora.text");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Date fechora = new Date();
        arch.escribir("Historial_calculadora.text","nuevo "+fechora);
        this.lb1.setText("Respuesta...");
        this.txtOperador.setText("");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        arch.abrirarchivo("Manueal de Uso.pdf");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLDMform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLDMform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLDMform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLDMform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLDMform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btdivi;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmas;
    private javax.swing.JButton btmenos;
    private javax.swing.JButton btpunto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel lb1;
    private javax.swing.JButton tb0;
    private javax.swing.JButton tbmulti;
    private javax.swing.JTextField txtOperador;
    // End of variables declaration//GEN-END:variables

  

   
}
